services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_SERVERNAME=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=stm_auth

    networks:
      - my-network

  db:
    image: mysql:5.7
    volumes:
      - ./database/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stm_auth
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
